name: ms5_andon
description: MS5.0 Andon Mobile Application
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  go_router: ^13.2.0

  # Networking
  dio: ^5.4.1
  socket_io_client: ^2.0.3

  # State Management
  flutter_riverpod: ^2.5.0

  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0

  # Authentication
  flutter_secure_storage: ^9.0.0
  flutter_appauth: ^6.0.4

  # UI Components
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

  # Media
  camera: ^0.10.5
  image_picker: ^1.0.7

  # Notifications
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.19

  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  connectivity_plus: ^5.0.2
  device_info_plus: ^10.0.1
  package_info_plus: ^5.0.1

  # Monitoring
  sentry_flutter: ^7.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
